/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;

import deepspace.LootToUI;

/**
 *
 * @author carmenc
 */
public class Loot extends javax.swing.JPanel {

    /**
     * Creates new form loot
     */
    public Loot() {
        initComponents();
    }
    
    public void setLoot(LootToUI l){
        nhangars.setText(Integer.toString(l.getnHangars()));
        nmedals.setText(Integer.toString(l.getnMedals()));
        nshields.setText(Integer.toString(l.getnShields()));
        nsupplies.setText(Integer.toString(l.getnSupplies()));
        nweapons.setText(Integer.toString(l.getnWeapons()));
        repaint();
        //revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textLoot = new javax.swing.JTextField();
        hangars = new javax.swing.JTextField();
        medals = new javax.swing.JTextField();
        shields = new javax.swing.JTextField();
        supplies = new javax.swing.JTextField();
        weapons = new javax.swing.JTextField();
        nhangars = new javax.swing.JLabel();
        nmedals = new javax.swing.JLabel();
        nshields = new javax.swing.JLabel();
        nsupplies = new javax.swing.JLabel();
        nweapons = new javax.swing.JLabel();

        textLoot.setText("Received Loot: ");

        hangars.setText("Hangars: ");

        medals.setText("Medals: ");

        shields.setText("Shields: ");

        supplies.setText("Supplies: ");
        supplies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliesActionPerformed(evt);
            }
        });

        weapons.setText("Weapons: ");
        weapons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weaponsActionPerformed(evt);
            }
        });

        nhangars.setText("nhangars");

        nmedals.setText("nmedals");

        nshields.setText("nshields");

        nsupplies.setText("nsupplies");

        nweapons.setText("nweapons");
        nweapons.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(weapons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hangars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textLoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(shields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nshields)
                    .addComponent(nhangars)
                    .addComponent(nmedals)
                    .addComponent(nsupplies)
                    .addComponent(nweapons))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textLoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hangars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nhangars))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nmedals))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nshields))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nsupplies))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weapons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nweapons))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void suppliesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliesActionPerformed

    private void weaponsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weaponsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weaponsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hangars;
    private javax.swing.JTextField medals;
    private javax.swing.JLabel nhangars;
    private javax.swing.JLabel nmedals;
    private javax.swing.JLabel nshields;
    private javax.swing.JLabel nsupplies;
    private javax.swing.JLabel nweapons;
    private javax.swing.JTextField shields;
    private javax.swing.JTextField supplies;
    private javax.swing.JTextField textLoot;
    private javax.swing.JTextField weapons;
    // End of variables declaration//GEN-END:variables
}
