/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.GUI;

import java.util.ArrayList;

/**
 *
 * @author carmenc
 */
public class MainWindow extends javax.swing.JFrame implements View.View{

    /**
     * Creates new form MainWindow
     */
    private static MainWindow instance = null;
    public static MainWindow getInstance () {
        if (instance == null) instance = new MainWindow();
        return instance;
    }
    
    public MainWindow() {
        initComponents();
    }
    
    //implementar métodos heredados de la interfaz View
    @Override
    public void updateView(){
        
    }
    
    @Override
    public void showView(){
        this.setVisible(true);
    }
    
    @Override
    public ArrayList<String> readNamePlayers(){
        NamesCapture namesCapt= new NamesCapture(this);
        return namesCapt.readNamePlayers();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
