/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;

import deepspace.SpaceStationToUI;
import deepspace.DamageToUI;
import deepspace.HangarToUI;
import deepspace.WeaponToUI;
import deepspace.ShieldToUI;
import java.util.ArrayList;
import controller.Controller;
import deepspace.GameState;

/**
 *
 * @author carmenc
 */
public class SpaceStationView extends javax.swing.JPanel {

    DamageView dview;
    HangarView hview;
    
    
    /**
     * Creates new form SpaceStationView
     */
    public SpaceStationView() {
        initComponents();
    }
    
    public void enabledButtons(SpaceStationToUI ss){
        boolean hAv = (ss.getHangar())!=null;
        boolean shieldsInHangar = false;
        boolean weaponsInHangar=false;
        boolean elementsInHangar=false;
        
        if(hAv){
            weaponsInHangar = (!ss.getHangar().getWeapons().isEmpty());
            shieldsInHangar = (!ss.getHangar().getShieldBoosters().isEmpty());
            
            elementsInHangar = weaponsInHangar || shieldsInHangar;
        }
        
        boolean weaponsMounted = !ss.getWeapons().isEmpty();
        boolean shieldsMounted = !ss.getShieldBoosters().isEmpty();
        
        GameState gs=Controller.getInstance().getState();
        
        
    }
    
    public void setStation(SpaceStationToUI ss){
        nammoPower.setText(Float.toString(ss.getAmmoPower()));
        nfuel.setText(Float.toString(ss.getFuelUnits()));
        nmedals.setText(Integer.toString(ss.getnMedals()));
        nshields.setText(Float.toString(ss.getShieldPower()));
        name.setText(ss.getName());
        
        ArrayList<WeaponToUI> nweapons=ss.getWeapons();
        ArrayList<ShieldToUI> nshields = ss.getShieldBoosters();
        
        ShieldsView sview;
        WeaponsView wview;
        
        for(int i = 0; i < nweapons.size(); i++){
            wview = new WeaponsView();
            wview.setWeapon(nweapons.get(i));
            panelMountedWeapons.add(wview);
        }
        
        for(int i = 0; i < nshields.size(); i++){
            sview = new ShieldsView();
            sview.setShieldBooster(nshields.get(i));
            panelMountedShields.add(sview);
        }
        
        dview=new DamageView();
        dview.setDamage(ss.getPendingDamage());
        panelPendingDamage.add(dview);
        
        hview = new HangarView();
        hview.setHangar(ss.getHangar());
        panelHangar.add(hview);
        
        enabledButtons(ss);
        
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spacestation = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        ammoPower = new javax.swing.JTextField();
        fuelUnits = new javax.swing.JTextField();
        medals = new javax.swing.JTextField();
        shieldpower = new javax.swing.JTextField();
        nammoPower = new javax.swing.JLabel();
        nfuel = new javax.swing.JLabel();
        nmedals = new javax.swing.JLabel();
        nshields = new javax.swing.JLabel();
        weaponsMounted = new javax.swing.JScrollPane();
        panelMountedWeapons = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelMountedShields = new javax.swing.JPanel();
        textMountedWeapons = new javax.swing.JTextField();
        textMountedShields = new javax.swing.JTextField();
        discardHangarBut = new javax.swing.JButton();
        panelHangar = new javax.swing.JPanel();
        panelPendingDamage = new javax.swing.JPanel();

        spacestation.setText("Space Station: ");

        name.setText("name");

        ammoPower.setText("Ammonition Power:");

        fuelUnits.setText("Fuel Units:");

        medals.setText("Medals: ");

        shieldpower.setText("Shiled Power: ");

        nammoPower.setText("nammoPower");

        nfuel.setText("nfuel");

        nmedals.setText("nmedals");

        nshields.setText("nshields");

        javax.swing.GroupLayout panelMountedWeaponsLayout = new javax.swing.GroupLayout(panelMountedWeapons);
        panelMountedWeapons.setLayout(panelMountedWeaponsLayout);
        panelMountedWeaponsLayout.setHorizontalGroup(
            panelMountedWeaponsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );
        panelMountedWeaponsLayout.setVerticalGroup(
            panelMountedWeaponsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );

        weaponsMounted.setViewportView(panelMountedWeapons);

        javax.swing.GroupLayout panelMountedShieldsLayout = new javax.swing.GroupLayout(panelMountedShields);
        panelMountedShields.setLayout(panelMountedShieldsLayout);
        panelMountedShieldsLayout.setHorizontalGroup(
            panelMountedShieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );
        panelMountedShieldsLayout.setVerticalGroup(
            panelMountedShieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelMountedShields);

        textMountedWeapons.setText("Mounted Weapons:");

        textMountedShields.setText("Mounted Shields:");

        discardHangarBut.setText("Discard Hangar");

        javax.swing.GroupLayout panelHangarLayout = new javax.swing.GroupLayout(panelHangar);
        panelHangar.setLayout(panelHangarLayout);
        panelHangarLayout.setHorizontalGroup(
            panelHangarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelHangarLayout.setVerticalGroup(
            panelHangarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelPendingDamageLayout = new javax.swing.GroupLayout(panelPendingDamage);
        panelPendingDamage.setLayout(panelPendingDamageLayout);
        panelPendingDamageLayout.setHorizontalGroup(
            panelPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelPendingDamageLayout.setVerticalGroup(
            panelPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(weaponsMounted)
            .addComponent(jScrollPane1)
            .addComponent(panelHangar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ammoPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spacestation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fuelUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shieldpower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name)
                            .addComponent(nammoPower)
                            .addComponent(nfuel)
                            .addComponent(nmedals)
                            .addComponent(nshields)))
                    .addComponent(textMountedWeapons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMountedShields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discardHangarBut))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelPendingDamage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spacestation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ammoPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nammoPower))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fuelUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nfuel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nmedals))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shieldpower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nshields))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textMountedWeapons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weaponsMounted, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textMountedShields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(panelHangar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(discardHangarBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(panelPendingDamage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ammoPower;
    private javax.swing.JButton discardHangarBut;
    private javax.swing.JTextField fuelUnits;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField medals;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nammoPower;
    private javax.swing.JLabel nfuel;
    private javax.swing.JLabel nmedals;
    private javax.swing.JLabel nshields;
    private javax.swing.JPanel panelHangar;
    private javax.swing.JPanel panelMountedShields;
    private javax.swing.JPanel panelMountedWeapons;
    private javax.swing.JPanel panelPendingDamage;
    private javax.swing.JTextField shieldpower;
    private javax.swing.JTextField spacestation;
    private javax.swing.JTextField textMountedShields;
    private javax.swing.JTextField textMountedWeapons;
    private javax.swing.JScrollPane weaponsMounted;
    // End of variables declaration//GEN-END:variables
}
